-- P2: idempotency table backing the Idempotency-Key header.
-- VARCHAR(4000) + GENERATED BY DEFAULT AS IDENTITY are both H2- and Postgres-safe.
CREATE TABLE idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_body VARCHAR(4000),
    created_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_idempotency_key UNIQUE (idempotency_key)
);
